apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 921562758039.dkr.ecr.us-east-2.amazonaws.com/myapp-repo
  newName: 921562758039.dkr.ecr.us-east-2.amazonaws.com/myapp-repo
  newTag: aa68ef2e
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
